# Generated by Django 5.2 on 2025-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_resposnd', models.CharField(max_length=255)),
                ('bot_response', models.TextField()),
            ],
        ),
    ]
